title: Mi GitHub Page
author: daniel-beta
email: danielbetancur@ingenieros.com
description: > # this means to ignore newlines until "baseurl:"
  Portafolio Daniel Betancur Rodríguez, desarrollador Web.

# social links
twitter_username: danielbetancurr # DO NOT include the @ character, or else the build will fail!
github_username:  daniel-beta # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
